spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/expense_manager?options=-c%20TimeZone=Asia/Kolkata
    username: expense
    password: expense
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080
